### ISSUE TITLE
Compilation of tantivy dependency failed because all compressors are devatived

### ISSUE THREAD

**Issue by ahcm** [phiresky/tantivy-wasm#1]
Hi,

very cool project.
I tried to compile it (after I adjusted the tantivy to my local path) and got the following compile error:
"all compressors are deactivated via feature-flags, check Cargo.toml for available decompressors."
for tantivy.
Did you change something in tantivy that I also have to?

Thanks
Andy

**Comment by phiresky** [comment]
Did you use my fork of tantivy? I got the same error when I tried to accidentaly compile with tantivy master, but my fork is based on 0.14

**Comment by ahcm** [comment]
Ah, OK. I used master.

**Comment by ahcm** [comment]
After checking out your tantivy and tantivy-fst it compiled fine.
