### ISSUE TITLE
Locally running the demo hangs

### ISSUE THREAD

**Issue by bakkot** [phiresky/tantivy-wasm#2]
I built this project with your forks of `tantivy` and `tantify-fst`. I couldn't figure out the requirements for the index files so I downloaded them off your hosted demo. Running `npx http-server` looked like it worked, but it got to the `bf92c5e40ac948299bc68912773ab04f.store` request and then hung - in Chrome the tab is stuck at max CPU and the request for that file shows up as `pending` permanently.

Before then it does print a few lines:

```
Getting info for term "horac"
Fetching document ids and frequencies matching term Term(field=1,text="\u{0}\u{0}\u{0}\u{1}horac")
Getting info for term "horac"
Fetching document ids and frequencies matching term Term(field=2,text="\u{0}\u{0}\u{0}\u{2}horac")
Getting info for term "slughorn"
Fetching document ids and frequencies matching term Term(field=1,text="\u{0}\u{0}\u{0}\u{1}slughorn")
Getting info for term "slughorn"
Fetching document ids and frequencies matching term Term(field=2,text="\u{0}\u{0}\u{0}\u{2}slughorn")
```

(This happens whether or not I apply the `decoder.patch` in this directory.)

I tried doing it with my own index following [the example in the tantivy-cli docs](https://github.com/tantivy-search/tantivy-cli#creating-the-index--new), but it failed with `OpenReadError(IOError { io_error: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }, filepath: "dd8df16bbcac45078e02b00c027bcff8.term" })`; no idea what that indicates. Does the index need to be built in a certain way?

I realize you only intended this as a demo, so if you don't want to spend time helping me debug don't worry about it, but if you happen to know what's wrong I'd appreciate it.

**Comment by phiresky** [comment]
> I couldn't figure out the requirements for the index files

What do you mean with index files?

**Comment by phiresky** [comment]
you mean the database itself?

when you generate the db yourself, you need to use version 0.14 of tantivy-cli, i'd guess that's your problem there (the newer version i think changes the file format a bit?)

**Comment by phiresky** [comment]
with the endless loop, i'm not sure what that is. could be that `http-server` does not support range requests or something

**Comment by bakkot** [comment]
> when you generate the db yourself, you need to use version 0.14 of tantivy-cli, i'd guess that's your problem there (the newer version i think changes the file format a bit?)

Ahah, yup, that was the problem. (I also needed to pass `-t 1` so it would create only a single segment.)

Unfortunately it runs into the same infinite loop. `http-server` does support range requests - I'm using it successfully with `sql.js-httpvfs`. I suppose it's possible that the server is the problem somehow, though. Do you have a preferred local http server you test with?

**Comment by phiresky** [comment]
I tested it with nginx, but I don't remember exactly why I switched from http-server. Maybe because it doesn't support multi-range http range requests? What's the http request it gets stuck at?

**Comment by bakkot** [comment]
> What's the http request it gets stuck at?

It's the request for the `.store` file. I have [a fork with the build artifacts committed](https://github.com/bakkot/tantivy-wasm), if that helps.

(That fork is also [served from gh-pages](https://bakkot.github.io/tantivy-wasm/dist/), but that's broken for a different reason: `get_file_len Error: server uses gzip or doesn't have length"`.)

**Comment by bakkot** [comment]
It does work with `nginx`, turns out! So I guess `http-server` was the problem.

Guess I'll see if I can get it working on github pages now.

**Comment by phiresky** [comment]
great! let me know when you get it working, i'd be interested in seeing the results

**Comment by ashutoshsaboo** [comment]
Hey @bakkot - just came across this. Were you able to get it working on github pages eventually? Just confirming, is this the repo - https://github.com/bakkot/tantivy-wasm - with all your latest changes? 

Quite an interesting project btw @phiresky! :)

**Comment by bakkot** [comment]
@ashutoshsaboo I never actually tried. I decided [SQL was good enough](https://github.com/phiresky/sql.js-httpvfs) for my purposes and let it rest there.

That is the right repo, though.
